classdef architecture

properties

    %%% Architecture
    geometry = 'random'                     % 'random', 'hex_lattice'
    strand_typology assignmentmode = assignmentmode();
    types = struct(...
        'natom_type',           1, ...
        'nbond_type',           5, ...
        'atype_mode',           'frac', ...
        'btype_mode',           'frac', ...
        'atom_count',           0, ...
        'bond_count',           0, ...
        'atom_frac',            1, ...
        'bond_frac',            1, ...
        'connectivity',         [ ], ...
        'atype_sel_method',     'random', ... 
        'btype_sel_method',     'random' ... 
    );
    lattice_spacing =           6;
    spacing_multiplier_mode =   'auto';
    spacing_multiplier =        1.2;
    lattice_disorder_level =     1;
    lattice_disorder_maxfrac =  0.4;
    lattice_max_del_per_node =  1;
    lattice_min_degree_keep =   5;

    rho_atom =                  0.0078;

end

end