classdef assignmentmode
    properties

        auto = true;

        mode = 'mono';

        %%% Mono assignment
        mono = struct(...
            'value',                20 ...
        );

        %%% Uniform assignment
        uniform = struct(...
            'min_value',            5, ...
            'max_value',            40 ...
        );

        %%% Polydisperse assignment
        poly = struct(...
            'method',               'pmf', ...
            'min_value',            1, ...
            'align_to_length',      'ascend', ...
            'rounding',             'round', ...
            'range_method',         'rank', ...
            'target_min',           5, ...
            'target_max',           120, ...
            'pmf_min',              20, ...
            'pmf_max',              120, ...
            'pmf_mean',             40, ...
            'pmf_cut_mode',         'cap', ...
            'pmf_integerize_rule',  'largest_remainder' ...
            );

        %%% Bimodal assignment
        bimodal = struct(...
            'mean_1',               35, ...
            'mean_2',               60, ...
            'std_1',                10, ...
            'std_2',                5, ...
            'method',               'gaussian', ...
            'height_mode',          'prob', ...
            'height_prob',          1.0, ...
            'height_count',         2, ...
            'long_first',           true, ...
            'double_network_flag',  true, ...
            'alpha',                5.0, ...
            'auto_1_flag',          false, ...
            'auto_2_flag',          true, ...
            'bin_window_method',    'manual', ...
            'manual_dev_type',      'mixed', ...
            'stdR_1',               3, ...
            'stdR_2',               10, ...
            'lam_1',                0.2, ...
            'lam_2',                0.5 ...
        );

    end
end