%% NetworkGen configuration script
%% Generated by the NetworkGen config builder
%% https://soft-matter-lab.github.io/networkgen

net = network();
net.Nreplicates = 1;

%% ---- Domain ----
net.domain.b                 = 1.6;
net.domain.Lx                = 150*3;
net.domain.Ly                = 150*3;
net.domain.scale             = 1;
net.domain.boundary          = 'fixed';
net.domain.write_location    = './networks';
net.domain.lammps_data_file  = 'PolyNetwork';
net.domain.lammps_viz_file   = 'PolyVisual';
net.domain.smp_number        = 1;
net.domain.seed              = 1852;

%% ---- Architecture ----
net.architecture.geometry           = 'random';
net.architecture.rho_atom           = 0.0078;
net.peratom.Max_peratom_bond        = 6;

%% ---- Strand typology ----
net.architecture.strand_typology.mode = 'poly';
net.architecture.strand_typology.poly.method   = 'pmf';
net.architecture.strand_typology.poly.pmf_mean = 5;
net.architecture.strand_typology.poly.pmf_min  = 3;
net.architecture.strand_typology.poly.pmf_max  = 8;
net.architecture.strand_typology.poly.rounding       = 'round';
net.architecture.strand_typology.poly.align_to_length = 'none';

net.architecture.spacing_multiplier_mode = 'fixed';
net.architecture.spacing_multiplier = 1.87;

%% ---- Perbond ----
net.perbond.kuhn.auto = true;

%% ---- Defects ----
net.defect.density_mode       = 'area_frac';
net.defect.void_area_frac     = 0.85;
net.defect.size_dist          = 'exponential';
net.defect.radius_mean        = 20;  %20
net.defect.radius_std         = 8;   %8
net.defect.radius_min         = 5;   %5
net.defect.radius_max         = 50;  %50
net.defect.shape_roughness    = 0.3;
net.defect.shape_n_modes      = 2;
net.defect.void_overlap       = false;
net.defect.center_distribution = 'clustered';
net.defect.n_cluster_parents  = 8;
net.defect.cluster_spread     = 10;
net.defect.margin_frac        = 0;  % was 0.15
net.defect.prune_isolated     = true;
net.defect.sparse_network     = true;
net.defect.wall_thickness     = 37.5; % was 37.5
net.defect.clamp_thickness    = 0.10;
net.defect.bridge_width       = 0.4;  % was 0.4

net.defect.thinning             = true;
net.defect.thinning_radius      = 8.75;  % 14
net.defect.thinning_target_frac = 0.01;  %
net.defect.thinning_min_keep    = 0.005;

%
net.defect.bridging            = true;
net.defect.bridge_max_dist     = 20;    % 10b ≈ 16 units
net.defect.bridge_min_spacing  = 8;
net.defect.bridge_void_thresh  = 0.20;  % midpoint density fraction to qualify as void
net.defect.bridge_perp_width   = 5;     % 0 = auto (~1 × node spacing ≈ 11 units)
net.defect.bridge_max_degree   = 0;     % 0 = use Max_peratom_bond

%net.defect.bridge_max_bonds = 50;    % add at most 50 bridge bonds
%% ---- Flags ----
net.flags.isave      = true;
net.flags.iplot      = false;
net.flags.ilog       = true;
net.flags.savemode   = true;
net.flags.imanualseed = true;
net.flags.idefect    = true;
net.flags.ipotential = true;
net.flags.idumpsettings = true;
net.flags.iversbose_settings = true;


%% ---- Generate ----
net.generateNetwork();
