%% NetworkGen configuration script
%% Generated by the NetworkGen config builder
%% https://soft-matter-lab.github.io/networkgen

net = network();
net.Nreplicates = 1;

%% ---- Domain ----
net.domain.b                 = 1.6;
net.domain.Lx                = 100;
net.domain.Ly                = 100;
net.domain.scale             = 1;
net.domain.boundary          = 'fixed';
net.domain.write_location    = './networks';
net.domain.lammps_data_file  = 'PolyNetwork';
net.domain.lammps_viz_file   = 'PolyVisual';
net.domain.smp_number        = 1;

%% ---- Architecture ----
net.architecture.geometry           = 'random';
net.architecture.rho_atom           = 0.0078;
net.peratom.Max_peratom_bond        = 6;

%% ---- Strand typology ----
net.architecture.strand_typology.mode = 'mono';
net.architecture.strand_typology.mono.value = 20;

%% ---- Perbond ----
net.perbond.kuhn.auto = true;

%% ---- Flags ----
net.flags.isave      = true;
net.flags.iplot      = true;
net.flags.ilog       = true;
net.flags.savemode   = true;
net.flags.imanualseed = false;
net.flags.idefect    = false;
net.flags.ipotential = false;

%% ---- Generate ----
net.generateNetwork();
