classdef network < handle

properties

    % Define properites and set default parameters

    %%% replicate count
    Nreplicates = 1;

    %%% Flags
    flags = struct(...
        'isave',                true, ...
        'iplot',                true, ...
        'ilog',                 true, ...
        'savemode',             true, ...
        'imanualseed',          false, ...
        'idefect',              false, ...
        'ipotential',           true ...
    );

    %%% Domain
    domain = struct(...
        'b',                                1.6, ...
        'dimension',                        2, ...
        'Lx',                               150, ...
        'Ly',                               150, ...
        'Lz',                               10, ...
        'scale',                            1, ...
        'boundary',                         'fixed', ...
        'seed',                             12345, ...
        'write_location',                   './networks', ...
        'lammps_data_file',                 'PolyNetwork', ...
        'lammps_viz_file',                  'PolyVisual', ...
        'bond_table_file',                  'bond', ...
        'smp_number',                       1, ...
        'xlo',                              [], ...
        'xhi',                              [], ...
        'ylo',                              [], ...
        'yhi',                              [], ...
        'zlo',                              [], ...
        'zhi',                              [], ...
        'Max_atom',                         [], ...
        'Max_bond',                         [], ...
        'node_scatter_max_tries',           [], ...
        'bond_global_try_limit',            [], ...
        'max_attempts_without_progress',    [], ...
        'max_tries_per_node_sample',        [], ...
        'min_node_sep',                     [], ...
        'min_node_sep2',                    [] ...
    );

    %%% Architecture subclass
    architecture architecture 

    %%% Per/atom
    peratom = struct(...
        'Max_peratom_bond',[], ...
        'min_degree_keep',2 ...
    );

    %%% Per/bond subclass
    perbond bondstyle

    %%% Defect
    defect = struct(...
        'density_mode',         'area_frac', ...
        'n_voids',              0, ...
        'void_area_frac',       0.75, ...
        'size_dist',            'gaussian', ...
        'radius_mean',          12, ...
        'radius_std',           4, ...
        'radius_min',           2, ...
        'radius_max',           30, ...
        'shape_roughness',      0.3, ...
        'shape_n_modes',        2, ...
        'void_overlap',         false, ...
        'bridge_width',         1, ...
        'center_distribution', 'clustered', ...
        'n_cluster_parents',    2, ...
        'cluster_spread',       10, ...
        'margin_frac',          0.15, ...
        'prune_isolated',       true, ...
        'sparse_network',       true, ...
        'wall_thickness',       18, ...
        'clamp_thickness',      0.12 ...
    );

    %%% Potential
    pot = struct(...
        'k_LD',                 0.414, ...
        'N_rho',                100000, ...
        'rho_min',              0.0, ...
        'rho_max',              500 ...
    );

    %%% networklog helper class
    log networklog

end

methods

    % Explicitly initialize subclass objects in the constructor
    function obj = network()
        warning off backtrace % Suppress stack trace
        obj.architecture = architecture();
        obj.perbond = bondstyle();
        obj.log = networklog();
    end

    function [] = generateNetwork(obj)

        %%% Loop over replicates
        for ii= 1:obj.Nreplicates %Nreps

            % ---------------------------------------------------------
            % 1. Prepare replicate-specific information
            % ---------------------------------------------------------
            localPrepareReplicate(obj, ii, obj.Nreplicates);

            obj.log.setReplicate(ii); % Set current replicate in log for tracking

            % ---------------------------------------------------------
            % 2. Construct domain
            % ---------------------------------------------------------
            SetupDomain(obj);
            syncKuhnAssignmentFromTopology(obj);
            % New version of SetupDomain should read from obj.domain, obj.arch, ...
            
            % ---------------------------------------------------------
            % 3. Add atoms
            % ---------------------------------------------------------
            [Atoms, LatticeData] = AddAtoms(obj);
            % Decides internally to do random or hex based on geometry flag
            % ---------------------------------------------------------
            % 4. Assign per/atom
            % ---------------------------------------------------------
            %Atoms = AssignPerAtom(obj, Atoms);
            % AssignPerAtom should read per-atom settings (if any) from obj
           

            % ---------------------------------------------------------
            % 5. Add bonds
            % ---------------------------------------------------------
            [Atoms, Bonds] = AddBonds(obj, Atoms, LatticeData);
            syncKuhnAssignmentFromTopology(obj);

            % ---------------------------------------------------------
            % 6. Assign per/bond
            % ---------------------------------------------------------
            Nvec = AssignPerBond(obj, Bonds, Atoms);
            % AssignPerBond should read obj.perbond.* settings and assign

            % ---------------------------------------------------------
            % 7. Add defects
            % ---------------------------------------------------------
            [Atoms, Bonds, Nvec] = AddDefects(obj, Atoms, Bonds, Nvec);
            % AddDefects should read obj.defect

            % ---------------------------------------------------------
            % 8. Clean-up network
            % ---------------------------------------------------------
            [Atoms, Bonds, Nvec] = CleanupNetwork(obj, Atoms, Bonds, Nvec);
            % CleanupNetwork can prune isolated nodes, rebuild connectivity,
            % update Nvec, etc.


            % ---------------------------------------------------------
            % 9. Construct local density potential
            % ---------------------------------------------------------
            LDpot = ConstructLDPotential(obj, Atoms, Bonds, Nvec);

            % ---------------------------------------------------------
            % 10. Scale domain if needed
            % ---------------------------------------------------------
            [Atoms, Bonds] = ScaleDomain(obj, Atoms, Bonds);
            
            % ---------------------------------------------------------
            % 11. Show visualization and statistics
            % ---------------------------------------------------------
            VisualizeNetwork(obj, Atoms, Bonds, Nvec);
            % VisualizeNetwork should check obj.flags.iplot internally

            % ---------------------------------------------------------
            % 12. Computes
            % ---------------------------------------------------------
            order = ComputeOrder(obj, Atoms, Bonds);

            % ---------------------------------------------------------
            % 13. Write data files
            % ---------------------------------------------------------
            WriteDataFiles(obj, Atoms, Bonds, Nvec, LDpot);

            % ---------------------------------------------------------
            % 14. Write and clear logs
            % ---------------------------------------------------------
            outdir = obj.domain.write_location;
            obj.log.recordNetworkStats(Atoms, Bonds, Nvec, obj, LDpot, order);
            % Collects statistics across arrays and stores in log object for this replicate
            
            obj.log.writeLogs( fullfile(outdir, obj.log.console_log_file), ...
                   fullfile(outdir, obj.log.network_log_file) );
            obj.log.clear();
        end

    end


end
end