classdef network < handle

properties

    % Define properites and set default parameters

    %%% Flags
    flags = struct(...
        'isave',                true, ...
        'iplot',                true, ...
        'ilog',                 true, ...
        'savemode',             true, ...
        'imanualseed',          false, ...
        'idefect',              false, ...
        'ipotential',           false ...
    );

    %%% Domain
    domain = struct(...
        'b',                    1.6, ...
        'dimension',            2, ...
        'Lx',                   150, ...
        'Ly',                   150, ...
        'Lz',                   1, ...
        'scale',                1.0, ...
        'boundary',             'fixed', ...
        'seed',                 12345, ...
        'write_location',       './networks', ...
        'lammps_data_file',     'PolyNetwork', ...
        'lammps_viz_file',      'PolyVisual', ...
        'bond_table_file',      'bond', ...
        'smp_number',           1 ...
    );

    %%% Architecture subclass
    architecture architecture 

    %%% Per/atom
    peratom = struct(...
        'max_peratom_bond',     5 ...
    );

    %%% Per/bond subclass
    perbond bondstyle

    %%% Defect
    defect = struct(...
        'density_mode',         'area_frac', ...
        'n_voids',              0, ...
        'void_area_frac',       0.75, ...
        'size_dist',            'gaussian', ...
        'radius_mean',          12, ...
        'radius_std',           4, ...
        'radius_min',           2, ...
        'radius_max',           30, ...
        'shape_roughness',      0.3, ...
        'shape_n_modes',        2, ...
        'void_overlap',         false, ...
        'bridge_width',         1, ...
        'center_distribution', 'clustered', ...
        'n_cluster_parents',    2, ...
        'cluster_spread',       10, ...
        'margin_frac',          0.15, ...
        'prune_isolated',       true, ...
        'sparse_network',       true, ...
        'wall_thickness',       18, ...
        'clamp_thickness',      0.12 ...
    );

    %%% Potential
    pot = struct(...
        'k_LD',                 0.414, ...
        'N_rho',                100000, ...
        'rho_min',              0.0, ...
        'rho_max',              500 ...
    );

    %%% log
    log = struct(...
    );

end

methods

    % Explicitly initialize subclass objects in the constructor
    function obj = network()
        obj.architecture = architecture();
        obj.perbond = bondstyle();
    end

    function [] = generateNetwork(obj)

        obj.domain.scale = 5;
        %%% Loop over replicates
        for ii=1 %Nreps

            % -----------------------------------%
            %1. Prepare replicate-specific information

            %2. Constuct domain

            %3. Add atoms

            %4. Assign per/atom

            %5. Add bonds

            %6. Assign per/bond

            %7. Add defects

            %8. Clean-up network


            % -----------------------------------%
            %9. Construct local density potential

            %10. Scale domain if needed
            
            % -----------------------------------%
            %11. Show visualization and statistics

            %12. Computes

            %13. Write data files

            % -----------------------------------%

        end

    end


end
end